### ISSUE TITLE
State of the project

### ISSUE THREAD

**Issue by kofronpi** [commondream/payday#46]
Hello,

Before using this gem for a professional project, I'd like to know if it's still maintained, and what's the plan if it's not.

Latest commit is from last year and some issues and pull-requests are open for a while now. The demo app has been offline for several months, and the codeship CI badge is broken.  

I think invoicing is something many RoR shops need and `payday` seems to be the last man standing in these regards :)

Thanks

**Comment by commondream** [comment]
Payday's been stable in several apps for a while now, and because of that I'd say it's being maintained but also meets its goals and isn't actively receiving attention. I try to build projects that I think can reach a complete status rather than having to give them attention infinitely.

The one place where there are problems is with UTF handling. Unfortunately the font that Payday uses by default doesn't have a very large character set, and I haven't had time to approach font changes, but also haven't had much of a need for them. I'll gladly accept a well tested PR with font customization.

**Comment by kofronpi** [comment]
@commondream thank you for your prompt answer. I'm gonna test the gem with rails 5.0 ! I'll have a look if I run into issues with UTF handling.

**Comment by kirantpatil** [comment]
@kofronpi, any updates of your testing the gem with rails 5 ?

Are you using it in your production app ?

Or Have you considered using any other invoice gems or engines for rails 5 ?

Thanks.

**Comment by kofronpi** [comment]
@francois-ferrandis would be better at answering that now as he took over the project ;)
